[package]
name = "snaz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]



[dev-dependencies]
smaz = "0.1.0"
shoco-rs = "0.1.1"