[package]
name = "sss"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1.0.152", features = ["derive"]}
bincode = "1.3.3"



[dev-dependencies]
smaz = "0.1.0"
shoco-rs = "0.1.1"